name: journey
description: metro booking
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^2.1.0
  carousel_slider: ^4.1.1
  cloud_firestore: ^3.1.18
  cupertino_icons: ^1.0.2
  dotted_line: ^3.1.0
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  firebase_storage: ^10.2.18
  flutter_polyline_points: ^1.0.0
  flutter_stripe: ^3.2.0
  flutter_svg: ^1.1.1+1
  font_awesome_flutter: ^10.1.0
  get: ^4.6.5
  google_fonts: ^3.0.1
  google_map_polyline_new: ^0.3.0+2
  google_maps_flutter: ^2.1.8
  http: ^0.13.4
  intl: ^0.17.0
  permission_handler: ^9.2.0
  searchable_listview: ^1.6.0
  shared_preferences: ^2.0.15
  sliding_up_panel: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  icons_launcher: ^2.0.0-beta.2

icons_launcher:
  image_path: 'images/icon.png'
  ios: true
  android: true

flutter:
  uses-material-design: true
  assets:
    - images/
